// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LinkOrErr interface {
	IsLinkOrErr()
}

type AuthPayload struct {
	Token   *string `json:"token,omitempty"`
	User    *User   `json:"user,omitempty"`
	Message string  `json:"message"`
}

type Err struct {
	ErrMsg string `json:"errMsg"`
}

func (Err) IsLinkOrErr() {}

type Link struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

func (Link) IsLinkOrErr() {}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Links []*Link `json:"links,omitempty"`
}
